version: "3.8"

services:

  database_testenode: 
    image: postgres
    container_name: database_testenode
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=testenode
      - POSTGRES_DB=testenode
    volumes: 
      - pgdata:/data/postgres
    
  app: 
    build: .
    container_name: testenode
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app      
    links:
      - database_testenode
    depends_on: 
      - database_testenode
    

volumes: 
  pgdata: 
    driver: local